server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5432/customer
    username: 'user'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
